#include "xmpp_core.h"
#include <string.h>

room_t rooms[MAX_ROOMS];

/* ------------------------------------------------------------------
 * handle_handshake_logic
 *
 * Called when the client opens (or re-opens after SASL) an XML stream.
 * We respond with our own opening <stream:stream> header followed by
 * the <stream:features> block.
 *
 * Stream opening:
 *   RFC 6120 §4.2  — Stream negotiation overview
 *     https://datatracker.ietf.org/doc/html/rfc6120#section-4.2
 *   RFC 6120 §4.7  — Stream attributes
 *     https://datatracker.ietf.org/doc/html/rfc6120#section-4.7
 *   RFC 6120 §4.7.3 — 'id' attribute: MUST be generated by the server,
 *     MUST be unique per stream, and MUST be hard to predict.
 *     secure_random_u32() satisfies this via hw_trng_read() (hardware
 *     TRNG) with an xorshift64* CSPRNG fallback.  See libc_glue.c.
 *     https://datatracker.ietf.org/doc/html/rfc6120#section-4.7.3
 *   RFC 6120 §4.7.5 — 'version' attribute MUST be "1.0"
 *     https://datatracker.ietf.org/doc/html/rfc6120#section-4.7.5
 *
 * Stream features (pre-auth):
 *   RFC 6120 §4.3   — <stream:features> rules: server MUST include all
 *     features the client can use at this point.
 *     https://datatracker.ietf.org/doc/html/rfc6120#section-4.3
 *   RFC 6120 §5     — STARTTLS feature; we omit it (no TLS).
 *     If TLS is ever added it MUST be listed first and SHOULD be
 *     marked <required/> for non-localhost connections.
 *     https://datatracker.ietf.org/doc/html/rfc6120#section-5.3
 *   RFC 6120 §6.4.1 — Exchange of Stream Headers and Stream Features:
 *     SASL <mechanisms> advertisement in stream:features.
 *     https://datatracker.ietf.org/doc/html/rfc6120#section-6.4.1
 *
 * Stream features (post-auth):
 *   RFC 6120 §7.2  — After SASL the server MUST offer <bind>
 *     https://datatracker.ietf.org/doc/html/rfc6120#section-7.2
 *   RFC 6121 §3.1  — <session> feature (optional/legacy; many clients
 *     expect it. RFC 6121 §3.1 marks it as optional for servers to
 *     advertise, but advertising it is harmless.)
 *     https://datatracker.ietf.org/doc/html/rfc6121#section-3.1
 *
 * TODO: RFC 6120 §4.9.1 — on receiving a malformed opening element
 *   send a <stream:error> before closing. Currently we just ignore it.
 *   https://datatracker.ietf.org/doc/html/rfc6120#section-4.9.1
 * ------------------------------------------------------------------ */
void handle_handshake_logic(xmpp_client_ctx_t *ctx) {
    char response[512];

    /* RFC 6120 §4.7.3 — stream id: MUST be unique and hard to predict.
     * secure_random_u32() tries hw_trng_read() first (real hardware
     * entropy), then falls back to an xorshift64* CSPRNG seeded from
     * hardware entropy.  See libc_glue.c for the full description.
     * https://datatracker.ietf.org/doc/html/rfc6120#section-4.7.3 */
    unsigned int stream_id = secure_random_u32();

    if (ctx->authenticated) {
        /* Post-SASL stream: offer bind (required) and session (legacy).
         * RFC 6120 §7.2  — bind MUST be present after SASL.
         * RFC 6121 §3.1  — session is optional but widely expected. */
        snprintf(response, sizeof(response),
            "<?xml version='1.0'?>"
            "<stream:stream from='%s' id='%u' version='1.0' "
            "xml:lang='en' "
            "xmlns='jabber:client' "
            "xmlns:stream='http://etherx.jabber.org/streams'>"
            "<stream:features>"
              "<bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'/>"
              /* RFC 6121 §3.1 — <session> is legacy; comment out once
               * all target clients no longer require it. */
              "<session xmlns='urn:ietf:params:xml:ns:xmpp-session'/>"
            "</stream:features>",
            XMPP_DOMAIN, stream_id);
    }
    else {
        /* Pre-auth stream: offer SASL mechanisms.
         * RFC 6120 §6.4.1 — Exchange of Stream Headers and Stream
         *   Features: server advertises available mechanisms.
         *   https://datatracker.ietf.org/doc/html/rfc6120#section-6.4.1
         * RFC 6120 §6.3.4 — Mechanism Offers: each <mechanism> name is a
         *   registered IANA SASL mechanism name (case-sensitive, uppercase).
         *   https://datatracker.ietf.org/doc/html/rfc6120#section-6.3.4
         * RFC 6120 §6.3.3 — ANONYMOUS allows login without credentials;
         *   sufficient for a local-only embedded server.
         *   PLAIN credentials travel in cleartext — acceptable only
         *   over a TLS-protected stream (RFC 6120 §13.8.4).
         *   https://datatracker.ietf.org/doc/html/rfc6120#section-13.8.4
         * TODO: add STARTTLS feature before SASL mechanisms when TLS
         *   is available (RFC 6120 §5.3).
         *   https://datatracker.ietf.org/doc/html/rfc6120#section-5.3 */
        snprintf(response, sizeof(response),
            "<?xml version='1.0'?>"
            "<stream:stream from='%s' id='%u' version='1.0' "
            "xml:lang='en' "
            "xmlns='jabber:client' "
            "xmlns:stream='http://etherx.jabber.org/streams'>"
            "<stream:features>"
              "<mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>"
                "<mechanism>ANONYMOUS</mechanism>"
                "<mechanism>PLAIN</mechanism>"
              "</mechanisms>"
            "</stream:features>",
            XMPP_DOMAIN, stream_id);
    }

    /* TODO: RFC 6120 §4.9.1 — define and send <stream:error> conditions:
     *   <invalid-namespace/>   if xmlns or xmlns:stream is wrong
     *   <invalid-xml/>         if the stream header is malformed
     *   <unsupported-version/> if client sends version != "1.0"
     *   https://datatracker.ietf.org/doc/html/rfc6120#section-4.9.1 */
    send_raw(ctx, response);
}

/* ------------------------------------------------------------------
 * handle_sasl_success
 *
 * Sends the SASL <success/> element and transitions state.
 *
 * RFC 6120 §6.4.6 — SASL Success
 *   The server sends <success xmlns='urn:ietf:params:xml:ns:xmpp-sasl'/>.
 *   After this, the initiating entity MUST open a new XML stream.
 *   The server MUST treat all stream state as reset (new stream ID etc.).
 *   https://datatracker.ietf.org/doc/html/rfc6120#section-6.4.6
 *
 * NOTE: We handle the client's mandatory stream re-open via the
 *   strncmp("<stream:stream", ...) check in xmpp_recv_callback which
 *   calls handle_handshake_logic() again. This correctly implements the
 *   "stream restart" requirement from RFC 6120 §6.4.6.
 * ------------------------------------------------------------------ */
void handle_sasl_success(xmpp_client_ctx_t *ctx) {
    /* RFC 6120 §6.4.6 — success element namespace is xmpp-sasl */
    const char *resp = "<success xmlns='urn:ietf:params:xml:ns:xmpp-sasl'/>";

    xmpp_log("SEND", resp, strlen(resp));

    tcp_write(ctx->pcb, resp, strlen(resp), TCP_WRITE_FLAG_COPY);

    tcp_output(ctx->pcb);

    /* RFC 6120 §6.4.6 — server resets its state for the stream */
    ctx->authenticated = 1;
    ctx->state = STATE_AUTHENTICATED;
}

/* ------------------------------------------------------------------
 * xmpp_recv_callback
 *
 * lwIP TCP receive callback. Accumulates raw bytes into rx_buffer and
 * drives the parse-route loop.
 *
 * RFC 6120 §4.1   — The XML stream is a single long-lived XML document;
 *   stanza boundaries are determined by XML structure, not TCP framing.
 *   https://datatracker.ietf.org/doc/html/rfc6120#section-4.1
 *
 * Receiving data (stream opening detection):
 *   RFC 6120 §4.2  — Client initiates by sending <?xml ...?> followed
 *   by <stream:stream ...>. We detect this with strncmp/strstr below.
 *   https://datatracker.ietf.org/doc/html/rfc6120#section-4.2
 *
 * Buffer overflow handling (FIX §3 LOW):
 *   RFC 6120 §4.9.3.14 — <policy-violation/>: server MUST send a
 *   stream error and close the stream when a policy limit is exceeded.
 *   We now send <stream:error><policy-violation/></stream:error> then
 *   close the TCP connection instead of silently dropping.
 *   https://datatracker.ietf.org/doc/html/rfc6120#section-4.9.3.14
 *
 * Connection close (p == NULL):
 *   RFC 6120 §4.4  — Either party may close the stream by sending
 *   </stream:stream>; TCP FIN without the close element is also handled
 *   here (we just close the PCB).
 *   https://datatracker.ietf.org/doc/html/rfc6120#section-4.4
 *
 * SASL stanza routing during STATE_CONNECTED:
 *   RFC 6120 §6.4.2 — client sends <auth mechanism='...'>payload</auth>
 *   RFC 6120 §6.4.1 — xmlns is urn:ietf:params:xml:ns:xmpp-sasl
 *   https://datatracker.ietf.org/doc/html/rfc6120#section-6.4.2
 *   TODO: also validate SASL error cases listed in:
 *   RFC 6120 §6.5    — SASL errors (<not-authorized/>, <incorrect-encoding/>, etc.)
 *   RFC 6120 §13.9.1 — Security considerations for SASL
 *   https://datatracker.ietf.org/doc/html/rfc6120#section-6.5
 *
 * Pool exhaustion handling (FIX §3 LOW):
 *   RFC 6120 §4.9.3.17 — <resource-constraint/>: when the stanza pool
 *   is exhausted, we send a stream error and close the connection rather
 *   than silently discarding the stanza.
 *   https://datatracker.ietf.org/doc/html/rfc6120#section-4.9.3.17
 * ------------------------------------------------------------------ */
err_t xmpp_recv_callback(void *arg, struct tcp_pcb *pcb, struct pbuf *p, err_t err) {
    xmpp_client_ctx_t *ctx = (xmpp_client_ctx_t*)arg;

    if (!p) {
        /* RFC 6120 §4.4 — remote closed TCP without </stream:stream>;
         * clean up silently. */
        tcp_close(pcb);

        return ERR_OK;
    }

    xmpp_log("RECV", (char*)p->payload, p->len);

    if (ctx->rx_pos + (int)p->len < (int)(sizeof(ctx->rx_buffer) - 1)) {
        memcpy(ctx->rx_buffer + ctx->rx_pos, p->payload, p->len);

        ctx->rx_pos += p->len;
        ctx->rx_buffer[ctx->rx_pos] = '\0';
    }
    else {
        /* FIX (§3 LOW): Buffer full — RFC 6120 §4.9.3.14 requires a
         * <policy-violation/> stream error followed by closing the
         * connection rather than silently dropping data. */
        printf("[XMPP] Buffer Overflow! rx_pos=%d, incoming=%d — sending policy-violation and closing.\n",
               ctx->rx_pos, p->len);

        tcp_recved(pcb, p->len);

        pbuf_free(p);

        const char *stream_err =
            "<stream:error>"
              "<policy-violation xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>"
            "</stream:error>"
            "</stream:stream>";

        /* RFC 6120 §4.9.3.14 — send stream error then close */
        tcp_write(pcb, stream_err, strlen(stream_err), TCP_WRITE_FLAG_COPY);

        tcp_output(pcb);

        tcp_close(pcb);

        return ERR_OK;
    }

    /* RFC 6120 §4.1 — acknowledge received bytes to the TCP stack */
    tcp_recved(pcb, p->len);

    pbuf_free(p);

    while (ctx->rx_pos > 0) {
        /* Strip leading whitespace; RFC 6120 §11.7 permits whitespace
         * between top-level elements for keep-alive ("whitespace ping"). */
        int shift = 0;

        while (shift < ctx->rx_pos) {
            char c = ctx->rx_buffer[shift];

            if (c != ' ' && c != '\n' && c != '\r' && c != '\t'){
                break;
            }

            shift++;
        }

        if (shift > 0) {
            memmove(ctx->rx_buffer, ctx->rx_buffer + shift, ctx->rx_pos - shift);

            ctx->rx_pos -= shift;

            ctx->rx_buffer[ctx->rx_pos] = '\0';
        }

        if (ctx->rx_pos == 0) {
            break;
        }

        /* Stream (re-)open detection.
         * RFC 6120 §4.2  — client MUST send <?xml?> + <stream:stream> to open.
         * RFC 6120 §6.4.6 — client MUST re-open after SASL <success/>.
         * We consume the entire buffer here because the stream opening
         * element is never "complete" XML — it is deliberately left open
         * for the lifetime of the session. */
        if (strncmp(ctx->rx_buffer, "<?xml", 5) == 0 || strstr(ctx->rx_buffer, "<stream:stream")) {
            handle_handshake_logic(ctx);

            ctx->rx_pos = 0;

            return ERR_OK;
        }

        int bytes_consumed = 0;

        parse_null_reason_t reason;
        xmpp_stanza_t *stanza = parse_xml_stream(ctx->rx_buffer, ctx->rx_pos, &bytes_consumed, &reason);

        if (stanza) {
            if (ctx->state == STATE_CONNECTED) {
                /* RFC 6120 §6.4.2 — only SASL <auth> is valid before
                 * authentication is complete.
                 * TODO: RFC 6120 §6.5 — handle <abort/> element
                 * and respond with <failure><aborted/></failure>.
                 * TODO: RFC 6120 §6.5.7 — handle invalid mechanism with
                 * <failure><invalid-mechanism/></failure>. */
                if (strcmp(stanza->xmlns, "urn:ietf:params:xml:ns:xmpp-sasl") == 0) {
                    handle_sasl(ctx, stanza);
                }
            }
            else {
                xmpp_route_stanza(ctx, stanza);
            }

            xmpp_free_stanza(stanza);

            /* Slide the consumed bytes out of the buffer */
            if (bytes_consumed > 0) {
                memmove(ctx->rx_buffer, ctx->rx_buffer + bytes_consumed, ctx->rx_pos - bytes_consumed);

                ctx->rx_pos -= bytes_consumed;
                ctx->rx_buffer[ctx->rx_pos] = '\0';
            }
        }
        else {
            /* FIX (§3 LOW): If parse_xml_stream returned NULL because
             * xmpp_alloc_stanza() exhausted the pool (bytes_consumed > 0
             * but stanza is NULL), send RFC 6120 §4.9.3.17 resource-constraint
             * stream error and close the connection.
             * If NULL is due to an incomplete stanza, wait for more data. */
            if (reason == PARSE_NO_MEMORY) {
                /* Pool exhausted — RFC 6120 §4.9.3.17 */
                printf("[XMPP] Stanza pool exhausted — sending resource-constraint and closing.\n");

                const char *stream_err =
                    "<stream:error>"
                      "<resource-constraint xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>"
                    "</stream:error>"
                    "</stream:stream>";

                tcp_write(pcb, stream_err, strlen(stream_err), TCP_WRITE_FLAG_COPY);
                
                tcp_output(pcb);
                
                tcp_close(pcb);

                return ERR_OK;
            }

            /* Incomplete stanza — wait for more data */
            break;
        }
    }

    return ERR_OK;
}

/* ------------------------------------------------------------------
 * xmpp_accept_callback
 *
 * lwIP TCP accept callback — allocates a client context from the pool.
 *
 * RFC 6120 §3   — Client-to-server connections use port 5222 (IANA).
 *   https://datatracker.ietf.org/doc/html/rfc6120#section-3
 *
 * FIX (§3 CRITICAL): ctx is now zeroed with memset() before use.
 * Without this, when slot N+MAX_USERS is reused, stale rx_buffer,
 * rx_pos, state, authenticated, username, and full_jid from the
 * previous occupant would persist, causing the new client to inherit
 * the old client's session state.
 *
 * Additionally, if the slot being reused still has a live pcb from a
 * previous client, we call tcp_close() on it before overwriting the
 * pointer, preventing a resource leak where the old connection is
 * never formally closed.
 * ------------------------------------------------------------------ */
/* ------------------------------------------------------------------
 * Global client registry
 *
 * Previously a static local inside xmpp_accept_callback(); promoted
 * to file scope so that xmpp_handlers.c can iterate all active
 * connections for presence broadcasting (RFC 6121 §4.2.2).
 *
 * Slots are zero-initialised at startup (BSS).  A slot is considered
 * occupied when its pcb field is non-NULL AND its state is at least
 * STATE_SESSION.  xmpp_accept_callback() cycles through slots
 * round-robin; on reuse it closes any still-live TCP connection first.
 * ------------------------------------------------------------------ */
xmpp_client_ctx_t client_registry[MAX_USERS];

err_t xmpp_accept_callback(void *arg, struct tcp_pcb *newpcb, err_t err) {
    static int client_idx = 0;

    xmpp_client_ctx_t *ctx = &client_registry[client_idx];
    client_idx = (client_idx + 1) % MAX_USERS;

    /* FIX (§3 CRITICAL): Close the old connection if the slot is still
     * in use, then zero the entire context to prevent state bleed. */
    if (ctx->pcb != NULL) {
        /* Evict the previous occupant before reusing this slot. */
        tcp_close(ctx->pcb);
    }

    memset(ctx, 0, sizeof(*ctx));

    ctx->pcb = newpcb;
    ctx->state = STATE_CONNECTED;
    ctx->authenticated = 0;

    tcp_arg(newpcb, ctx);

    tcp_recv(newpcb, xmpp_recv_callback);

    return ERR_OK;
}

/* ------------------------------------------------------------------
 * xmpp_init_server
 *
 * Binds and starts listening on the XMPP client port.
 *
 * RFC 6120 §3.2  — Client-to-Server connections:
 *   TCP port 5222 (IANA registered as "xmpp-client").
 *   https://datatracker.ietf.org/doc/html/rfc6120#section-3.2
 *
 * TODO: RFC 6120 §5 — also listen on port 5223 for "Direct TLS"
 *   (legacy XEP-0035 / RFC 6120 §5.3.2) if TLS is added.
 * ------------------------------------------------------------------ */
void xmpp_init_server() {
    struct tcp_pcb *pcb = tcp_new();

    tcp_bind(pcb, IP_ADDR_ANY, 5222); /* RFC 6120 §3.2 — XMPP client port */

    pcb = tcp_listen(pcb);

    tcp_accept(pcb, xmpp_accept_callback);
}