#include "xmpp_core.h"
#include <string.h>

room_t rooms[MAX_ROOMS];

/* ------------------------------------------------------------------
 * handle_handshake_logic
 *
 * Called when the client opens (or re-opens after SASL) an XML stream.
 * We respond with our own opening <stream:stream> header followed by
 * the <stream:features> block.
 *
 * Stream opening:
 *   RFC 6120 §4.2  — Stream negotiation overview
 *     https://datatracker.ietf.org/doc/html/rfc6120#section-4.2
 *   RFC 6120 §4.7  — Stream attributes
 *     https://datatracker.ietf.org/doc/html/rfc6120#section-4.7
 *   RFC 6120 §4.7.3 — 'id' attribute: MUST be generated by the server,
 *     MUST be unique per stream, and MUST be hard to predict.
 *     secure_random_u32() satisfies this via hw_trng_read() (hardware
 *     TRNG) with an xorshift64* CSPRNG fallback.  See libc_glue.c.
 *     https://datatracker.ietf.org/doc/html/rfc6120#section-4.7.3
 *   RFC 6120 §4.7.5 — 'version' attribute MUST be "1.0"
 *     https://datatracker.ietf.org/doc/html/rfc6120#section-4.7.5
 *
 * Stream features (pre-auth):
 *   RFC 6120 §4.3   — <stream:features> rules: server MUST include all
 *     features the client can use at this point.
 *     https://datatracker.ietf.org/doc/html/rfc6120#section-4.3
 *   RFC 6120 §5     — STARTTLS feature; offered <required/> before any
 *     SASL mechanisms.  Implemented via mbedTLS in xmpp_tls.c.
 *     Pre-TLS: only <starttls><required/></starttls> is advertised.
 *     Post-TLS: SASL mechanisms are advertised; STARTTLS not re-offered.
 *     https://datatracker.ietf.org/doc/html/rfc6120#section-5
 *   RFC 6120 §13.8.4 — PLAIN MUST NOT be offered without TLS;
 *     enforced by withholding <mechanisms> until tls_established=1.
 *     https://datatracker.ietf.org/doc/html/rfc6120#section-13.8.4
 *   RFC 6120 §6.4.1 — Exchange of Stream Headers and Stream Features:
 *     SASL <mechanisms> advertisement in stream:features (post-TLS only).
 *     https://datatracker.ietf.org/doc/html/rfc6120#section-6.4.1
 *
 * Stream features (post-auth):
 *   RFC 6120 §7.2  — After SASL the server MUST offer <bind>
 *     https://datatracker.ietf.org/doc/html/rfc6120#section-7.2
 *   RFC 6121 §3.1  — <session> feature (optional/legacy; many clients
 *     expect it. RFC 6121 §3.1 marks it as optional for servers to
 *     advertise, but advertising it is harmless.)
 *     https://datatracker.ietf.org/doc/html/rfc6121#section-3.1
 *
 * Stream error (§4.9.1): implemented in xmpp_recv_callback via the
 *   bad_ns / bad_stream_ns / bad_ver checks that fire before calling
 *   this function, so by the time we reach here the opening element
 *   has already been validated.
 * ------------------------------------------------------------------ */
/* ------------------------------------------------------------------
 * extract_stream_attr
 *
 * Scans the raw rx_buffer for a named attribute in the <stream:stream>
 * tag and copies its value (single- or double-quoted) into out[out_max].
 *
 * Returns 1 on success, 0 if the attribute is absent or the buffer does
 * not yet contain the full opening tag.
 *
 * RFC 6120 §4.7 — stream attributes
 * ------------------------------------------------------------------ */
static int extract_stream_attr(const char *buf, const char *attr_name,
                                char *out, int out_max) {
    /* Build search key: " attr_name=" */
    char key[64];
    snprintf(key, sizeof(key), " %s=", attr_name);

    const char *p = strstr(buf, key);
    if (!p) return 0;

    p += strlen(key);           /* skip to the quote */
    char q = *p;                /* opening quote: ' or " */
    if (q != '\'' && q != '"') return 0;
    p++;                        /* skip opening quote */

    const char *end = strchr(p, q);
    if (!end) return 0;         /* closing quote not yet received */

    int len = (int)(end - p);
    if (len >= out_max) len = out_max - 1;
    strncpy(out, p, len);
    out[len] = '\0';
    return 1;
}

void handle_handshake_logic(xmpp_client_ctx_t *ctx) {
    char response[512];

    /* RFC 6120 §4.7.3 — stream id: MUST be unique and hard to predict.
     * secure_random_u32() tries hw_trng_read() first (real hardware
     * entropy), then falls back to an xorshift64* CSPRNG seeded from
     * hardware entropy.  See libc_glue.c for the full description.
     * https://datatracker.ietf.org/doc/html/rfc6120#section-4.7.3 */
    unsigned int stream_id = secure_random_u32();

        /* RFC 6120 §4.7.2 — build 'to=' for the response stream header.
         *
         * If the client sent a 'from=' attribute in its <stream:stream> header
         * we MUST echo it as 'to=' in our response.  If absent, MUST NOT include
         * 'to=' at all.  ctx->client_from is populated from rx_buffer by the
         * caller (xmpp_recv_callback) before invoking handle_handshake_logic().
         *
         * RFC 6120 §4.7.2 — https://datatracker.ietf.org/doc/html/rfc6120#section-4.7.2 */
        char to_attr[96] = "";   /* empty → omit from snprintf */
        if (ctx->client_from[0] != '\0') {
            snprintf(to_attr, sizeof(to_attr), " to='%s'", ctx->client_from);
        }

    if (ctx->authenticated) {
        /* Post-SASL stream: offer bind (required) and session (legacy).
         * RFC 6120 §7.2  — bind MUST be present after SASL.
         * RFC 6121 §3.1  — session is optional but widely expected.
         *
         * set STATE_BIND so that the bind IQ handler is
         * only reachable from this specific negotiation point.
         *   RFC 6120 §7 — Resource Binding is a one-time per-stream step.
         *   https://datatracker.ietf.org/doc/html/rfc6120#section-7 */
        ctx->state = STATE_BIND;

        snprintf(response, sizeof(response),
            "<?xml version='1.0'?>"
            "<stream:stream from='%s'%s id='%u' version='1.0' "
            "xml:lang='en' "
            "xmlns='jabber:client' "
            "xmlns:stream='http://etherx.jabber.org/streams'>"
            "<stream:features>"
              "<bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'/>"
              /* RFC 6121 §3.1 — <session> is legacy; comment out once
               * all target clients no longer require it. */
              "<session xmlns='urn:ietf:params:xml:ns:xmpp-session'/>"
              "<sm xmlns='urn:xmpp:sm:3'/>"
            "</stream:features>",
            XMPP_DOMAIN, to_attr, stream_id);
    }
    else if (ctx->tls_established) {
        /* TLS is live — now safe to offer SASL PLAIN (RFC 6120 §13.8.4).
         * STARTTLS is NOT offered again per RFC 6120 §5.2 step 5c.
         * RFC 6120 §6.4.1 — server advertises available mechanisms.
         *   https://datatracker.ietf.org/doc/html/rfc6120#section-6.4.1 */
        snprintf(response, sizeof(response),
            "<?xml version='1.0'?>"
            "<stream:stream from='%s'%s id='%u' version='1.0' "
            "xml:lang='en' "
            "xmlns='jabber:client' "
            "xmlns:stream='http://etherx.jabber.org/streams'>"
            "<stream:features>"
              "<mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>"
                "<mechanism>ANONYMOUS</mechanism>"
                "<mechanism>PLAIN</mechanism>"
              "</mechanisms>"
            "</stream:features>",
            XMPP_DOMAIN, to_attr, stream_id);
    }
    else {
        /* Pre-TLS stream: offer STARTTLS as REQUIRED.
         *
         * RFC 6120 §5.3.1 — STARTTLS MUST be the first feature listed.
         * RFC 6120 §5.3.2 — <required/> means the client MUST negotiate
         *   TLS before any other protocol exchange.
         * RFC 6120 §13.8.4 — PLAIN MUST NOT be offered without TLS;
         *   therefore no SASL mechanisms are listed here.
         *   https://datatracker.ietf.org/doc/html/rfc6120#section-5.3
         *   https://datatracker.ietf.org/doc/html/rfc6120#section-13.8.4 */
        snprintf(response, sizeof(response),
             "<?xml version='1.0'?>"
            "<stream:stream from='%s'%s id='%u' version='1.0' "
             "xml:lang='en' "
             "xmlns='jabber:client' "
             "xmlns:stream='http://etherx.jabber.org/streams'>"
             "<stream:features>"
               "<starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'>"
                 "<required/>"
               "</starttls>"
             "</stream:features>",
            XMPP_DOMAIN, to_attr, stream_id);
    }

    /* NOTE: RFC 6120 §4.9.1 stream-error conditions are enforced in
     * xmpp_recv_callback() (invalid-namespace / unsupported-version)
     * before this function is called.  By the time we reach here the
     * opening element has already been validated and accepted. */
    send_raw(ctx, response);

    /* Advance state after advertising:
     *   STATE_SASL — when SASL mechanisms were just offered (TLS live).
     *   STATE_CONNECTED stays — when STARTTLS was offered (waiting for
     *     <starttls/> from client before any SASL exchange).
     * The post-SASL and post-bind cases are handled by the STATE_BIND
     * assignment above. */
    if (!ctx->authenticated && ctx->tls_established) {
        ctx->state = STATE_SASL;
    }
}

/* RFC 6120 §6.4.6 — SASL Success: <success/> and stream-state reset
 * are now performed exclusively inside handle_sasl() in xmpp_handlers.c.
 *   https://datatracker.ietf.org/doc/html/rfc6120#section-6.4.6
 * ------------------------------------------------------------------ */

/* ------------------------------------------------------------------
 * xmpp_recv_callback
 *
 * lwIP TCP receive callback. Accumulates raw bytes into rx_buffer and
 * drives the parse-route loop.
 *
 * RFC 6120 §4.1   — The XML stream is a single long-lived XML document;
 *   stanza boundaries are determined by XML structure, not TCP framing.
 *   https://datatracker.ietf.org/doc/html/rfc6120#section-4.1
 *
 * Receiving data (stream opening detection):
 *   RFC 6120 §4.2  — Client initiates by sending <?xml ...?> followed
 *   by <stream:stream ...>. We detect this with strncmp/strstr below.
 *   https://datatracker.ietf.org/doc/html/rfc6120#section-4.2
 *
 * Buffer overflow handling:
 *   RFC 6120 §4.9.3.14 — <policy-violation/>: server MUST send a
 *   stream error and close the stream when a policy limit is exceeded.
 *   We now send <stream:error><policy-violation/></stream:error> then
 *   close the TCP connection instead of silently dropping.
 *   https://datatracker.ietf.org/doc/html/rfc6120#section-4.9.3.14
 *
 * Connection close (p == NULL):
 *   RFC 6120 §4.4  — Either party may close the stream by sending
 *   </stream:stream>; TCP FIN without the close element is also handled
 *   here (we just close the PCB).
 *   https://datatracker.ietf.org/doc/html/rfc6120#section-4.4
 *
 * SASL stanza routing during STATE_CONNECTED:
 *   RFC 6120 §6.4.2 — client sends <auth mechanism='...'>payload</auth>
 *   RFC 6120 §6.4.1 — xmlns is urn:ietf:params:xml:ns:xmpp-sasl
 *   https://datatracker.ietf.org/doc/html/rfc6120#section-6.4.2
 *   SASL error cases (RFC 6120 §6.5, §13.9.1) are fully handled in
 *   handle_sasl(): <not-authorized/>, <incorrect-encoding/>, and
 *   <invalid-mechanism/> are all implemented there.
 *
 * Pool exhaustion handling:
 *   RFC 6120 §4.9.3.17 — <resource-constraint/>: when the stanza pool
 *   is exhausted, we send a stream error and close the connection rather
 *   than silently discarding the stanza.
 *   https://datatracker.ietf.org/doc/html/rfc6120#section-4.9.3.17
 * ------------------------------------------------------------------ */
err_t xmpp_recv_callback(void *arg, struct tcp_pcb *pcb, struct pbuf *p, err_t err) {
    xmpp_client_ctx_t *ctx = (xmpp_client_ctx_t*)arg;

    if (!p) {
        /* RFC 6120 §4.4 — remote closed TCP without </stream:stream>;
         * clean up silently.
         *
         *ctx->pcb must be set to NULL after tcp_close().
         *
         * lwIP calls this callback with p == NULL when the remote side
         * closes the TCP connection.  All broadcaster loops in
         * xmpp_handlers.c guard against dead slots by checking
         * client_registry[i].pcb == NULL.  If we call tcp_close(pcb)
         * but leave ctx->pcb pointing at the now-freed PCB, those
         * loops will attempt to write to freed memory, causing undefined
         * behaviour (typically a crash or silent data corruption).
         *
         * Zeroing ctx->pcb here is the single fix needed because every
         * broadcast loop that iterates client_registry[] checks pcb for
         * NULL before dereferencing it.
         *
         * Also reset state to STATE_CONNECTED so that any stale slot
         * inspection (state >= STATE_SESSION checks) correctly treats
         * this slot as inactive even before it is reclaimed by
         * xmpp_accept_callback(). */
        tcp_close(pcb);

        /* Free mbedTLS resources before zeroing the context fields.
         * Safe to call when TLS was never initialised. */
        xmpp_tls_client_free(ctx);

        ctx->pcb = NULL; 
        ctx->state = STATE_CONNECTED; /* not SESSION — slot is inactive */

        return ERR_OK;
    }

    xmpp_log("RECV", (char*)p->payload, p->len);

    /* ── TLS: handshake in progress (STATE_STARTTLS) ───────────────────────
     * All bytes arriving in this state are raw TLS records.  Route them
     * directly to the TLS staging buffer; do NOT touch rx_buffer.
     * RFC 6120 §5.2.3 — after <proceed/> both sides immediately begin TLS.
     *   https://datatracker.ietf.org/doc/html/rfc6120#section-5.2.3 */
    if (ctx->state == STATE_STARTTLS) {
        tcp_recved(pcb, p->len);

        xmpp_tls_handshake_step(ctx, (const uint8_t *)p->payload, (int)p->len);
        
        pbuf_free(p);
        
        return ERR_OK;
    }

    /* ── TLS: established — decrypt encrypted bytes into rx_buffer ─────────
     * After decryption, fall through to the normal parse loop.  The
     * skip_plaintext_copy flag prevents the raw (still-encrypted) bytes
     * from being appended to rx_buffer a second time. */
    int skip_plaintext_copy = 0;

    if (ctx->tls_established) {
        tcp_recved(pcb, p->len);

        xmpp_tls_decrypt(ctx, (const uint8_t *)p->payload, (int)p->len);

        pbuf_free(p);
        
        skip_plaintext_copy = 1;
    }

    if (!skip_plaintext_copy) {
        if (ctx->rx_pos + (int)p->len < (int)(sizeof(ctx->rx_buffer) - 1)) {
            memcpy(ctx->rx_buffer + ctx->rx_pos, p->payload, p->len);

            ctx->rx_pos += p->len;
            ctx->rx_buffer[ctx->rx_pos] = '\0';
        }
        else {
            /* Buffer full — RFC 6120 §4.9.3.14 requires a
             * <policy-violation/> stream error followed by closing the
             * connection rather than silently dropping data. */
            printf("[XMPP] Buffer Overflow! rx_pos=%d, incoming=%d — sending policy-violation and closing.\n",
                   ctx->rx_pos, p->len);

            tcp_recved(pcb, p->len);

            pbuf_free(p);

            const char *stream_err =
                "<stream:error>"
                  "<policy-violation xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>"
                "</stream:error>"
                "</stream:stream>";

            /* RFC 6120 §4.9.3.14 — send stream error then close */
            tcp_write(pcb, stream_err, strlen(stream_err), TCP_WRITE_FLAG_COPY);

            tcp_output(pcb);

            tcp_close(pcb);

            ctx->pcb = NULL;
            ctx->state = STATE_CONNECTED;

            return ERR_OK;
        }

        /* RFC 6120 §4.1 — acknowledge received bytes to the TCP stack */
        tcp_recved(pcb, p->len);

        pbuf_free(p);
    }

    while (ctx->rx_pos > 0) {
        /* Strip leading whitespace; RFC 6120 §11.7 permits whitespace
         * between top-level elements for keep-alive ("whitespace ping"). */
        int shift = 0;

        while (shift < ctx->rx_pos) {
            char c = ctx->rx_buffer[shift];

            if (c != ' ' && c != '\n' && c != '\r' && c != '\t'){
                break;
            }

            shift++;
        }

        if (shift > 0) {
            memmove(ctx->rx_buffer, ctx->rx_buffer + shift, ctx->rx_pos - shift);

            ctx->rx_pos -= shift;

            ctx->rx_buffer[ctx->rx_pos] = '\0';
        }

        if (ctx->rx_pos == 0) {
            break;
        }

        /* STARTTLS element detection — RFC 6120 §5.2
         *
         * Detected pre-parse (like <abort/>) for reliability.  Only valid
         * in STATE_CONNECTED before TLS has been established.  The element
         * arrives as the first thing in rx_buffer after the initial stream
         * negotiation offers STARTTLS <required/>.
         *
         * On receiving <starttls/>:
         *   1. Send <proceed xmlns='urn:ietf:params:xml:ns:xmpp-tls'/>.
         *   2. Initialise per-client TLS context.
         *   3. Advance to STATE_STARTTLS; subsequent bytes are TLS records.
         *
         * If TLS init fails we send <failure/> and close (RFC 6120 §5.2.2).
         *   https://datatracker.ietf.org/doc/html/rfc6120#section-5.2 */
        if (ctx->state == STATE_CONNECTED && !ctx->tls_established && strncmp(ctx->rx_buffer, "<starttls", 9) == 0) {
            char *starttls_gt = strchr(ctx->rx_buffer, '>');

            if (!starttls_gt) {
                break;
            }

            /* Send <proceed/> — RFC 6120 §5.2.2 */
            const char *proceed = "<proceed xmlns='urn:ietf:params:xml:ns:xmpp-tls'/>";

            tcp_write(ctx->pcb, proceed, strlen(proceed), TCP_WRITE_FLAG_COPY);

            tcp_output(ctx->pcb);

            /* Initialise per-client TLS session */
            if (xmpp_tls_client_init(ctx) != 0) {
                /* TLS setup failed — RFC 6120 §5.2.2 send <failure/> */
                const char *fail = "<failure xmlns='urn:ietf:params:xml:ns:xmpp-tls'/>";
                
                tcp_write(ctx->pcb, fail, strlen(fail), TCP_WRITE_FLAG_COPY);
                
                tcp_output(ctx->pcb);
                
                tcp_close(ctx->pcb);
                
                ctx->pcb = NULL;
                ctx->state = STATE_CONNECTED;
                ctx->rx_pos = 0;
                
                return ERR_OK;
            }

            /* All subsequent bytes from this client are TLS records */
            ctx->state = STATE_STARTTLS;
            ctx->rx_pos = 0; /* discard anything before the starttls tag */

            return ERR_OK;
        }

        /* Stream (re-)open detection.
         * RFC 6120 §4.2  — client MUST send <?xml?> + <stream:stream> to open.
         * RFC 6120 §6.4.6 — client MUST re-open after SASL <success/>.
         * We consume the entire buffer here because the stream opening
         * element is never "complete" XML — it is deliberately left open
         * for the lifetime of the session.
         *
         * gate on connection state before scanning for
         * <stream:stream>.
         *
         * The old code ran strstr(rx_buffer, "<stream:stream") unconditionally
         * on every loop iteration, scanning the ENTIRE accumulated buffer
         * regardless of state.  A client in STATE_READY could exploit this by
         * embedding the literal text "<stream:stream xmlns='jabber:client'
         * xmlns:stream='http://etherx.jabber.org/streams' version='1.0'" inside
         * a <message> body.  The strstr would match inside the payload, all
         * three namespace/version checks would pass (the strings are present
         * in the buffer), handle_handshake_logic() would fire, and rx_pos would
         * be zeroed — discarding further stanzas in the same TCP segment and
         * corrupting the authenticated session state.
         *
         * A stream re-open is only legitimate in two states:
         *   STATE_CONNECTED     — initial stream open (RFC 6120 §4.2)
         *   STATE_AUTHENTICATED — mandatory post-SASL re-open (RFC 6120 §6.4.6)
         *
         * In all other states (STATE_BIND, STATE_SESSION, STATE_READY) the
         * buffer contains stanza data; the stream-open check must be skipped
         * so payload content cannot trigger it.
         *
         * Note: strncmp(rx_buffer, "<?xml", 5) is safer in isolation because
         * it only fires when those five bytes are at the very START of the
         * buffer — a stanza body will never begin with "<?xml".  It is kept
         * inside the state guard anyway so both arms are always gated together.
         *
         *   RFC 6120 §4.9.1  https://datatracker.ietf.org/doc/html/rfc6120#section-4.9.1 */
         

         /* ------------------------------------------------------------------
         * RFC 6120 §4.4 — Graceful stream close.
         *
         * When the client sends </stream:stream>, the server MUST reply with
         * its own </stream:stream> and then close the TCP connection.
         * Previously the server only handled TCP FIN (p == NULL path) and
        * silently ignored the XML close element.
         *
         * Detection: the buffer starts with "</stream:stream" or
         * "</stream>" (some old clients omit the namespace prefix).
         * We check only at the start of the buffer to prevent false matches
         * inside stanza bodies.
         *
         *   RFC 6120 §4.4 — https://datatracker.ietf.org/doc/html/rfc6120#section-4.4
         * ------------------------------------------------------------------ */
        if (strncmp(ctx->rx_buffer, "</stream:stream", 15) == 0 ||
            strncmp(ctx->rx_buffer, "</stream>", 9) == 0) {

            /* Reply with our own close element */
            const char *close_tag = "</stream:stream>";
            if (ctx->tls_established) {
                /* Send through TLS layer */
                mbedtls_ssl_write(&ctx->tls_ssl,
                    (const unsigned char *)close_tag, strlen(close_tag));
                if (ctx->pcb) tcp_output(ctx->pcb);
                /* RFC 6120 §4.4 / TLS §7.2.1 — send close_notify */
                mbedtls_ssl_close_notify(&ctx->tls_ssl);
            } else {
                tcp_write(ctx->pcb, close_tag, strlen(close_tag),
                          TCP_WRITE_FLAG_COPY);
                tcp_output(ctx->pcb);
            }

            xmpp_tls_client_free(ctx);
            tcp_close(ctx->pcb);
            ctx->pcb = NULL;
            ctx->state = STATE_CONNECTED;
            ctx->rx_pos = 0;
            return ERR_OK;
        }
        if ((ctx->state == STATE_CONNECTED || ctx->state == STATE_AUTHENTICATED) && (strncmp(ctx->rx_buffer, "<?xml", 5) == 0 || strstr(ctx->rx_buffer, "<stream:stream"))) {
            /* ------------------------------------------------------------------
             * RFC 6120 §4.9.1 — validate the stream opening element
             * before accepting.  If required attributes are absent or wrong,
             * send the appropriate <stream:error> and close the connection.
             *
             * We check only when the <stream:stream> tag is actually present
             * in the buffer; if only the XML declaration arrived so far we
             * wait for more data so the check is meaningful.
             *
             * Conditions checked:
             *   <invalid-namespace/>   — xmlns != 'jabber:client' or
             *                            xmlns:stream wrong / absent
             *   <unsupported-version/> — version attribute absent or not "1.0"
             *                            (RFC 6120 §4.7.5 requires exactly "1.0")
             *
             *   RFC 6120 §4.9.1  https://datatracker.ietf.org/doc/html/rfc6120#section-4.9.1
             *   RFC 6120 §4.9.3.11 (invalid-namespace)
             *   RFC 6120 §4.9.3.22 (unsupported-version)
             * ------------------------------------------------------------------ */
            if (strstr(ctx->rx_buffer, "<stream:stream")) {
                /* ----------------------------------------------------------
                 * RFC 6120 §4.7.2 — Extract client's 'from=' attribute.
                 * Store it so handle_handshake_logic() can echo it as 'to='.
                 * Clear client_from first so a re-open without 'from=' does
                 * not inherit the value from a previous stream.
                 * ---------------------------------------------------------- */
                ctx->client_from[0] = '\0';
                extract_stream_attr(ctx->rx_buffer, "from",
                                    ctx->client_from, sizeof(ctx->client_from));

                /* ----------------------------------------------------------
                 * RFC 6120 §4.9.3.6 — host-unknown.
                 *
                 * The 'to=' attribute of the client's stream header MUST be
                 * a domain serviced by this server.  If absent or wrong, send
                 * <stream:error><host-unknown/></stream:error> and close.
                 *
                 * We only enforce this on the first (pre-TLS) stream open.
                 * After TLS is established the client already proved it reached
                 * the right host via the certificate's CN/SAN.
                 *
                 *   RFC 6120 §4.9.3.6
                 *   https://datatracker.ietf.org/doc/html/rfc6120#section-4.9.3.6
                 * ---------------------------------------------------------- */
                if (!ctx->tls_established && !ctx->authenticated) {
                    char stream_to[64] = "";
                    extract_stream_attr(ctx->rx_buffer, "to",
                                        stream_to, sizeof(stream_to));
                    if (stream_to[0] != '\0' &&
                        strcmp(stream_to, XMPP_DOMAIN) != 0) {
                        /* Build the stream open so the client can parse our error */
                        char err[512];
                        snprintf(err, sizeof(err),
                            "<?xml version='1.0'?>"
                            "<stream:stream from='" XMPP_DOMAIN "' id='0'"
                              " version='1.0' xml:lang='en'"
                              " xmlns='jabber:client'"
                              " xmlns:stream='http://etherx.jabber.org/streams'>"
                            "<stream:error>"
                              "<host-unknown"
                                " xmlns='urn:ietf:params:xml:ns:xmpp-streams'/>"
                            "</stream:error>"
                            "</stream:stream>");
                        tcp_write(ctx->pcb, err, strlen(err),
                                  TCP_WRITE_FLAG_COPY);
                        tcp_output(ctx->pcb);
                        tcp_close(ctx->pcb);
                        ctx->pcb = NULL;
                        ctx->rx_pos = 0;
                        return ERR_OK;
                    }
                }
                /* Check for required xmlns='jabber:client' */
                int bad_ns = (strstr(ctx->rx_buffer, "xmlns='jabber:client'") == NULL && strstr(ctx->rx_buffer, "xmlns=\"jabber:client\"") == NULL);

                /* Check for required xmlns:stream namespace URI */
                int bad_stream_ns = (strstr(ctx->rx_buffer, "xmlns:stream='http://etherx.jabber.org/streams'") == NULL &&
                                     strstr(ctx->rx_buffer, "xmlns:stream=\"http://etherx.jabber.org/streams\"") == NULL);

                /* Check for version='1.0' (RFC 6120 §4.7.5: MUST be "1.0") */
                int bad_ver = (strstr(ctx->rx_buffer, "version='1.0'") == NULL && strstr(ctx->rx_buffer, "version=\"1.0\"") == NULL);

                if (bad_ns || bad_stream_ns) {
                    /* RFC 6120 §4.9.3.11 — <invalid-namespace/> */
                    const char *err =
                        "<?xml version='1.0'?>"
                        "<stream:stream from='" XMPP_DOMAIN "' id='0' version='1.0' "
                          "xmlns='jabber:client' "
                          "xmlns:stream='http://etherx.jabber.org/streams'>"
                        "<stream:error>"
                          "<invalid-namespace "
                            "xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>"
                        "</stream:error>"
                        "</stream:stream>";

                    /* pbuf already freed above the while() loop */
                    tcp_write(ctx->pcb, err, strlen(err), TCP_WRITE_FLAG_COPY);

                    tcp_output(ctx->pcb);

                    tcp_close(ctx->pcb);

                    ctx->rx_pos = 0;

                    return ERR_OK;
                }

                if (bad_ver) {
                    /* RFC 6120 §4.9.3.22 — <unsupported-version/>
                     * Absent version attribute is treated as < 1.0 per §4.7.5. */
                    const char *err =
                        "<?xml version='1.0'?>"
                        "<stream:stream from='" XMPP_DOMAIN "' id='0' version='1.0' "
                          "xmlns='jabber:client' "
                          "xmlns:stream='http://etherx.jabber.org/streams'>"
                        "<stream:error>"
                          "<unsupported-version "
                            "xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>"
                        "</stream:error>"
                        "</stream:stream>";

                    tcp_write(ctx->pcb, err, strlen(err), TCP_WRITE_FLAG_COPY);

                    tcp_output(ctx->pcb);

                    tcp_close(ctx->pcb);

                    ctx->rx_pos = 0;

                    return ERR_OK;
                }
            }
            else {
                /* Only the <?xml?> declaration seen; <stream:stream> not yet
                 * received.  Wait for the rest of the stream open. */
                break;
            }

            handle_handshake_logic(ctx);

            ctx->rx_pos = 0;

            return ERR_OK;
        }

        /* ------------------------------------------------------------------
         * RFC 6120 §6.4.4 — SASL <abort/> handling.
         * If the client sends an <abort/> element during SASL negotiation,
         * the server MUST respond with <failure><aborted/></failure>.
         * We detect this BEFORE parsing because the <abort/> element's
         * namespace is an outer attribute that the parser does not capture
         * in stanza->xmlns for unknown element names.
         *   https://datatracker.ietf.org/doc/html/rfc6120#section-6.4.4
         *
         * This check only triggers in STATE_CONNECTED (pre-authentication)
         * where SASL exchange is valid; it is a no-op in all other states.
         * ------------------------------------------------------------------ */
        /* include STATE_SASL in the abort check.
         * <abort/> is a SASL-layer element valid throughout the SASL
         * exchange, which now spans STATE_CONNECTED → STATE_SASL.
         *   RFC 6120 §6.4.4
         *   https://datatracker.ietf.org/doc/html/rfc6120#section-6.4.4 */
        if ((ctx->state == STATE_CONNECTED || ctx->state == STATE_SASL) && strncmp(ctx->rx_buffer, "<abort", 6) == 0) {
            /* Find the end of the abort element (self-closing or with children) */
            char *gt = strchr(ctx->rx_buffer, '>');

            if (gt) {
                int abort_consumed = (int)((gt - ctx->rx_buffer) + 1);

                const char *abort_resp =
                    "<failure xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>"
                      "<aborted/>"
                    "</failure>";

                send_raw(ctx, abort_resp);

                /* Consume the abort element from the receive buffer */
                memmove(ctx->rx_buffer, ctx->rx_buffer + abort_consumed, ctx->rx_pos - abort_consumed);

                ctx->rx_pos -= abort_consumed;
                ctx->rx_buffer[ctx->rx_pos] = '\0';

                continue; /* restart the parse loop */
            }

            break; /* abort element incomplete — wait for more data */
        }

        // Handle XEP-0198 SM elements before stanza parsing
        if (ctx->state >= STATE_AUTHENTICATED) {
            if (xmpp_sm_handle_element(ctx)) {
                continue;  // SM element consumed; restart loop
            }
        }
        int bytes_consumed = 0;

        parse_null_reason_t reason;
        xmpp_stanza_t *stanza = parse_xml_stream(ctx->rx_buffer, ctx->rx_pos, &bytes_consumed, &reason);

        if (stanza) {
            if (ctx->state == STATE_CONNECTED || ctx->state == STATE_SASL) {
                /* RFC 6120 §6.4.2 — only SASL <auth> is valid before
                 * authentication is complete.
                 * <abort/> is handled above this loop (before parsing).
                 * <invalid-mechanism/> and <incorrect-encoding/> are
                 * handled inside handle_sasl().
                 *
                 * Without this, the state
                 * would advance to STATE_SASL but the dispatch check
                 * would still require STATE_CONNECTED, causing a
                 * legitimate <auth> to fall through to xmpp_route_stanza
                 * (which would reject it as an unrecognised IQ). */
                if (strcmp(stanza->xmlns, "urn:ietf:params:xml:ns:xmpp-sasl") == 0) {
                    handle_sasl(ctx, stanza);
                }
            }
            else {
                xmpp_route_stanza(ctx, stanza);

                xmpp_sm_on_stanza_received(ctx);
            }

            xmpp_free_stanza(stanza);

            /* Slide the consumed bytes out of the buffer */
            if (bytes_consumed > 0) {
                memmove(ctx->rx_buffer, ctx->rx_buffer + bytes_consumed, ctx->rx_pos - bytes_consumed);

                ctx->rx_pos -= bytes_consumed;
                ctx->rx_buffer[ctx->rx_pos] = '\0';
            }
        }
        else {
            /* If parse_xml_stream returned NULL because
             * xmpp_alloc_stanza() exhausted the pool (bytes_consumed > 0
             * but stanza is NULL), send RFC 6120 §4.9.3.17 resource-constraint
             * stream error and close the connection.
             * If NULL is due to an incomplete stanza, wait for more data. */
            if (reason == PARSE_NO_MEMORY) {
                /* Pool exhausted — RFC 6120 §4.9.3.17 */
                printf("[XMPP] Stanza pool exhausted — sending resource-constraint and closing.\n");

                const char *stream_err =
                    "<stream:error>"
                      "<resource-constraint xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>"
                    "</stream:error>"
                    "</stream:stream>";

                tcp_write(pcb, stream_err, strlen(stream_err), TCP_WRITE_FLAG_COPY);
                
                tcp_output(pcb);
                
                tcp_close(pcb);
                
                ctx->pcb = NULL;
                ctx->state = STATE_CONNECTED;

                return ERR_OK;
            }

            /* Incomplete stanza — wait for more data */
            break;
        }
    }

    return ERR_OK;
}

/* ------------------------------------------------------------------
 * xmpp_accept_callback
 *
 * lwIP TCP accept callback — allocates a client context from the pool.
 *
 * RFC 6120 §3   — Client-to-server connections use port 5222 (IANA).
 *   https://datatracker.ietf.org/doc/html/rfc6120#section-3
 *
 * ctx is now zeroed with memset() before use.
 * Without this, when slot N+MAX_USERS is reused, stale rx_buffer,
 * rx_pos, state, authenticated, username, and full_jid from the
 * previous occupant would persist, causing the new client to inherit
 * the old client's session state.
 *
 * Additionally, if the slot being reused still has a live pcb from a
 * previous client, we call tcp_close() on it before overwriting the
 * pointer, preventing a resource leak where the old connection is
 * never formally closed.
 * ------------------------------------------------------------------ */
/* ------------------------------------------------------------------
 * Global client registry
 *
 * Previously a static local inside xmpp_accept_callback(); promoted
 * to file scope so that xmpp_handlers.c can iterate all active
 * connections for presence broadcasting (RFC 6121 §4.2.2).
 *
 * Slots are zero-initialised at startup (BSS).  A slot is considered
 * occupied when its pcb field is non-NULL AND its state is at least
 * STATE_SESSION.  xmpp_accept_callback() cycles through slots
 * round-robin; on reuse it closes any still-live TCP connection first.
 * ------------------------------------------------------------------ */
xmpp_client_ctx_t client_registry[MAX_USERS];

err_t xmpp_accept_callback(void *arg, struct tcp_pcb *newpcb, err_t err) {
    static int client_idx = 0;

    xmpp_client_ctx_t *ctx = &client_registry[client_idx];
    client_idx = (client_idx + 1) % MAX_USERS;

    /* Close the old connection if the slot is still
     * in use, then zero the entire context to prevent state bleed. */
    if (ctx->pcb != NULL) {
        /* Evict the previous occupant before reusing this slot.
         * Free TLS context BEFORE tcp_close() and memset() so mbedTLS
         * can release its pool allocations cleanly. */
        xmpp_tls_client_free(ctx);

        tcp_close(ctx->pcb);
    }

    memset(ctx, 0, sizeof(*ctx));

    ctx->pcb = newpcb;
    ctx->state = STATE_CONNECTED;
    ctx->authenticated = 0;

    tcp_arg(newpcb, ctx);

    tcp_recv(newpcb, xmpp_recv_callback);

    return ERR_OK;
}

/* ------------------------------------------------------------------
 * xmpp_init_server
 *
 * Binds and starts listening on the XMPP client port.
 *
 * RFC 6120 §3.2  — Client-to-Server connections:
 *   TCP port 5222 (IANA registered as "xmpp-client").
 *   https://datatracker.ietf.org/doc/html/rfc6120#section-3.2
 *
 * NOTE (future work): When TLS is added, also bind port 5223 for
 *   "Direct TLS" / legacy XEP-0035 (RFC 6120 §5.3.2).
 * ------------------------------------------------------------------ */
void xmpp_init_server() {
    xmpp_persist_load_all();

    /* Initialise mbedTLS: generate key + self-signed cert, configure
     * the shared server SSL context.  Must complete before we start
     * accepting connections (key generation takes < 100 ms on a
     * typical embedded core).
     *   RFC 6120 §5 — STARTTLS
     *   https://datatracker.ietf.org/doc/html/rfc6120#section-5 */
    if (xmpp_tls_server_init() != 0) {
        /* TLS init failure is fatal — the server must not accept
         * connections without being able to offer STARTTLS
         * (RFC 6120 §5.3.2 <required/>). */
        printf("[XMPP] FATAL: TLS server init failed — halting.\n");
        
        for (;;) {} /* halt */
    }

    struct tcp_pcb *pcb = tcp_new();

    tcp_bind(pcb, IP_ADDR_ANY, 5222); /* RFC 6120 §3.2 — XMPP client port */

    pcb = tcp_listen(pcb);

    tcp_accept(pcb, xmpp_accept_callback);
}