#include "xmpp_core.h"
#include <string.h>

room_t rooms[MAX_ROOMS];

/* ------------------------------------------------------------------
 * handle_handshake_logic
 *
 * Called when the client opens (or re-opens after SASL) an XML stream.
 * We respond with our own opening <stream:stream> header followed by
 * the <stream:features> block.
 *
 * Stream opening:
 *   RFC 6120 §4.2  — Stream negotiation overview
 *     https://datatracker.ietf.org/doc/html/rfc6120#section-4.2
 *   RFC 6120 §4.7  — Stream attributes
 *     https://datatracker.ietf.org/doc/html/rfc6120#section-4.7
 *   RFC 6120 §4.7.3 — 'id' attribute: MUST be generated by the server,
 *     MUST be unique per stream, and MUST be hard to predict.
 *     rand() below does NOT satisfy "hard to predict" — replace with
 *     a CSPRNG (e.g. hardware RNG on your MCU) before production.
 *     https://datatracker.ietf.org/doc/html/rfc6120#section-4.7.3
 *   RFC 6120 §4.7.5 — 'version' attribute MUST be "1.0"
 *     https://datatracker.ietf.org/doc/html/rfc6120#section-4.7.5
 *
 * Stream features (pre-auth):
 *   RFC 6120 §4.3  — <stream:features> rules: server MUST include all
 *     features the client can use at this point.
 *     https://datatracker.ietf.org/doc/html/rfc6120#section-4.3
 *   RFC 6120 §5    — STARTTLS feature; we omit it (no TLS).
 *     If TLS is ever added it MUST be listed first and SHOULD be
 *     marked <required/> for non-localhost connections.
 *     https://datatracker.ietf.org/doc/html/rfc6120#section-5.3
 *   RFC 6120 §6.4.1 — SASL <mechanisms> advertisement
 *     https://datatracker.ietf.org/doc/html/rfc6120#section-6.4.1
 *
 * Stream features (post-auth):
 *   RFC 6120 §7.2  — After SASL the server MUST offer <bind>
 *     https://datatracker.ietf.org/doc/html/rfc6120#section-7.2
 *   RFC 6121 §3.1  — <session> feature (optional/legacy; many clients
 *     expect it. RFC 6121 §3.1 marks it as optional for servers to
 *     advertise, but advertising it is harmless.)
 *     https://datatracker.ietf.org/doc/html/rfc6121#section-3.1
 *
 * TODO: RFC 6120 §4.9.1 — on receiving a malformed opening element
 *   send a <stream:error> before closing. Currently we just ignore it.
 *   https://datatracker.ietf.org/doc/html/rfc6120#section-4.9.1
 * ------------------------------------------------------------------ */
void handle_handshake_logic(xmpp_client_ctx_t *ctx) {
    char response[512];

    /* RFC 6120 §4.7.3 — stream id: unique, unpredictable.
     * FIXME: rand() is not a CSPRNG; use hardware entropy source. */
    int stream_id = rand();

    if (ctx->authenticated) {
        /* Post-SASL stream: offer bind (required) and session (legacy).
         * RFC 6120 §7.2 — bind MUST be present after SASL.
         * RFC 6121 §3.1 — session is optional but widely expected. */
        snprintf(response, sizeof(response),
            "<?xml version='1.0'?>"
            "<stream:stream from='%s' id='%u' version='1.0' "
            "xml:lang='en' "
            "xmlns='jabber:client' "
            "xmlns:stream='http://etherx.jabber.org/streams'>"
            "<stream:features>"
              "<bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'/>"
              /* RFC 6121 §3.1 — <session> is legacy; comment out once
               * all target clients no longer require it. */
              "<session xmlns='urn:ietf:params:xml:ns:xmpp-session'/>"
            "</stream:features>",
            XMPP_DOMAIN, stream_id);
    }
    else {
        /* Pre-auth stream: offer SASL mechanisms.
         * RFC 6120 §6.3.5 — each <mechanism> name is a registered IANA
         *   SASL mechanism name (case-sensitive, uppercase).
         *   https://datatracker.ietf.org/doc/html/rfc6120#section-6.3.5
         * RFC 6120 §6.3.3 — ANONYMOUS allows login without credentials;
         *   sufficient for a local-only embedded server.
         *   PLAIN credentials travel in cleartext — acceptable only
         *   over a TLS-protected stream (RFC 6120 §13.8.4).
         *   https://datatracker.ietf.org/doc/html/rfc6120#section-13.8.4
         * TODO: add STARTTLS feature before SASL mechanisms when TLS
         *   is available (RFC 6120 §5.3).
         *   https://datatracker.ietf.org/doc/html/rfc6120#section-5.3 */
        snprintf(response, sizeof(response),
            "<?xml version='1.0'?>"
            "<stream:stream from='%s' id='%u' version='1.0' "
            "xml:lang='en' "
            "xmlns='jabber:client' "
            "xmlns:stream='http://etherx.jabber.org/streams'>"
            "<stream:features>"
              "<mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>"
                "<mechanism>ANONYMOUS</mechanism>"
                "<mechanism>PLAIN</mechanism>"
              "</mechanisms>"
            "</stream:features>",
            XMPP_DOMAIN, stream_id);
    }

    /* TODO: RFC 6120 §4.9.1 — define and send <stream:error> conditions:
     *   <invalid-namespace/>   if xmlns or xmlns:stream is wrong
     *   <invalid-xml/>         if the stream header is malformed
     *   <unsupported-version/> if client sends version != "1.0"
     *   https://datatracker.ietf.org/doc/html/rfc6120#section-4.9.1 */
    send_raw(ctx, response);
}

/* ------------------------------------------------------------------
 * handle_sasl_success
 *
 * Sends the SASL <success/> element and transitions state.
 *
 * RFC 6120 §6.4.6  — SASL Success
 *   The server sends <success xmlns='urn:ietf:params:xml:ns:xmpp-sasl'/>.
 *   After this, the initiating entity MUST open a new XML stream.
 *   The server MUST treat all stream state as reset (new stream ID etc.).
 *   https://datatracker.ietf.org/doc/html/rfc6120#section-6.4.6
 *
 * NOTE: We handle the client's mandatory stream re-open via the
 *   strncmp("<stream:stream", ...) check in xmpp_recv_callback which
 *   calls handle_handshake_logic() again. This correctly implements the
 *   "stream restart" requirement from RFC 6120 §6.4.6.
 * ------------------------------------------------------------------ */
void handle_sasl_success(xmpp_client_ctx_t *ctx) {
    /* RFC 6120 §6.4.6 — success element namespace is xmpp-sasl */
    const char *resp = "<success xmlns='urn:ietf:params:xml:ns:xmpp-sasl'/>";

    xmpp_log("SEND", resp, strlen(resp));

    tcp_write(ctx->pcb, resp, strlen(resp), TCP_WRITE_FLAG_COPY);

    tcp_output(ctx->pcb);

    /* RFC 6120 §6.4.6 — server resets its state for the stream */
    ctx->authenticated = 1;
    ctx->state = STATE_AUTHENTICATED;
}

/* ------------------------------------------------------------------
 * xmpp_recv_callback
 *
 * lwIP TCP receive callback. Accumulates raw bytes into rx_buffer and
 * drives the parse-route loop.
 *
 * RFC 6120 §4.1   — The XML stream is a single long-lived XML document;
 *   stanza boundaries are determined by XML structure, not TCP framing.
 *   https://datatracker.ietf.org/doc/html/rfc6120#section-4.1
 *
 * Receiving data (stream opening detection):
 *   RFC 6120 §4.2  — Client initiates by sending <?xml ...?> followed
 *   by <stream:stream ...>. We detect this with strncmp/strstr below.
 *   https://datatracker.ietf.org/doc/html/rfc6120#section-4.2
 *
 * Buffer overflow handling:
 *   Currently we reset rx_pos and drop the data silently.
 *   RFC 6120 §4.9.3.14 — <policy-violation/>: server SHOULD send a
 *   stream error and close the stream if a policy limit is exceeded.
 *   TODO: send <stream:error><policy-violation/></stream:error> then
 *   close the TCP connection instead of silently dropping.
 *   https://datatracker.ietf.org/doc/html/rfc6120#section-4.9.3.14
 *
 * Connection close (p == NULL):
 *   RFC 6120 §4.4  — Either party may close the stream by sending
 *   </stream:stream>; TCP FIN without the close element is also handled
 *   here (we just close the PCB).
 *   https://datatracker.ietf.org/doc/html/rfc6120#section-4.4
 *
 * SASL stanza routing during STATE_CONNECTED:
 *   RFC 6120 §6.3.3 — client sends <auth mechanism='...'>payload</auth>
 *   RFC 6120 §6.3.4 — xmlns is urn:ietf:params:xml:ns:xmpp-sasl
 *   https://datatracker.ietf.org/doc/html/rfc6120#section-6.3.3
 *   TODO: also validate SASL error cases listed in:
 *   RFC 6120 §6.5   — SASL errors (<not-authorized/>, <incorrect-encoding/>, etc.)
 *   RFC 6120 §13.9.1 — Security considerations for SASL
 *   https://datatracker.ietf.org/doc/html/rfc6120#section-6.5
 * ------------------------------------------------------------------ */
err_t xmpp_recv_callback(void *arg, struct tcp_pcb *pcb, struct pbuf *p, err_t err) {
    xmpp_client_ctx_t *ctx = (xmpp_client_ctx_t*)arg;

    if (!p) {
        /* RFC 6120 §4.4 — remote closed TCP without </stream:stream>;
         * clean up silently. */
        tcp_close(pcb);

        return ERR_OK;
    }

    xmpp_log("RECV", (char*)p->payload, p->len);

    if (ctx->rx_pos + (int)p->len < (int)(sizeof(ctx->rx_buffer) - 1)) {
        memcpy(ctx->rx_buffer + ctx->rx_pos, p->payload, p->len);

        ctx->rx_pos += p->len;
        ctx->rx_buffer[ctx->rx_pos] = '\0';
    }
    else {
        /* Buffer full — dropping incoming data.
         * TODO: RFC 6120 §4.9.3.14 — send <policy-violation/> stream error
         * and close the connection cleanly instead of dropping silently. */
        printf("[XMPP] Buffer Overflow! Dropping %d bytes. rx_pos=%d\n", p->len, ctx->rx_pos);

        ctx->rx_pos = 0;
    }

    /* RFC 6120 §4.1 — acknowledge received bytes to the TCP stack */
    tcp_recved(pcb, p->len);

    pbuf_free(p);

    while (ctx->rx_pos > 0) {
        /* Strip leading whitespace; RFC 6120 §11.7 permits whitespace
         * between top-level elements for keep-alive ("whitespace ping"). */
        int shift = 0;

        while (shift < ctx->rx_pos) {
            char c = ctx->rx_buffer[shift];

            if (c != ' ' && c != '\n' && c != '\r' && c != '\t'){
                break;
            }

            shift++;
        }

        if (shift > 0) {
            memmove(ctx->rx_buffer, ctx->rx_buffer + shift, ctx->rx_pos - shift);

            ctx->rx_pos -= shift;

            ctx->rx_buffer[ctx->rx_pos] = '\0';
        }

        if (ctx->rx_pos == 0) {
            break;
        }

        /* Stream (re-)open detection.
         * RFC 6120 §4.2  — client MUST send <?xml?> + <stream:stream> to open.
         * RFC 6120 §6.4.6 — client MUST re-open after SASL <success/>.
         * We consume the entire buffer here because the stream opening
         * element is never "complete" XML — it is deliberately left open
         * for the lifetime of the session. */
        if (strncmp(ctx->rx_buffer, "<?xml", 5) == 0 || strstr(ctx->rx_buffer, "<stream:stream")) {
            handle_handshake_logic(ctx);

            ctx->rx_pos = 0;

            return ERR_OK;
        }

        int bytes_consumed = 0;

        xmpp_stanza_t *stanza = parse_xml_stream(ctx->rx_buffer, ctx->rx_pos, &bytes_consumed);

        if (stanza) {
            if (ctx->state == STATE_CONNECTED) {
                /* RFC 6120 §6.3.3 — only SASL <auth> is valid before
                 * authentication is complete.
                 * TODO: RFC 6120 §6.5 — handle <abort/> element
                 * and respond with <failure><aborted/></failure>.
                 * TODO: RFC 6120 §6.5.5 — handle invalid mechanism with
                 * <failure><invalid-mechanism/></failure>. */
                if (strcmp(stanza->xmlns, "urn:ietf:params:xml:ns:xmpp-sasl") == 0) {
                    handle_sasl(ctx, stanza);
                }
            }
            else {
                xmpp_route_stanza(ctx, stanza);
            }

            xmpp_free_stanza(stanza);

            /* Slide the consumed bytes out of the buffer */
            if (bytes_consumed > 0) {
                memmove(ctx->rx_buffer, ctx->rx_buffer + bytes_consumed, ctx->rx_pos - bytes_consumed);

                ctx->rx_pos -= bytes_consumed;
                ctx->rx_buffer[ctx->rx_pos] = '\0';
            }
        }
        else {
            /* Incomplete stanza — wait for more data */
            break;
        }
    }

    return ERR_OK;
}

/* ------------------------------------------------------------------
 * xmpp_accept_callback
 *
 * lwIP TCP accept callback — allocates a client context from the pool.
 *
 * RFC 6120 §3   — Client-to-server connections use port 5222 (IANA).
 *   https://datatracker.ietf.org/doc/html/rfc6120#section-3
 *
 * SECURITY NOTE: The static pool with a wrapping index means that
 * connecting client N+MAX_USERS will silently reuse the slot of
 * client N — even if client N is still connected. The old client's
 * pcb will never be closed. Consider checking ctx->state != STATE_CONNECTED
 * (or that ctx->pcb is NULL) before reusing a slot, and calling
 * tcp_close() on the evicted connection.
 *
 * BUG: ctx is not zeroed before reuse. Stale rx_buffer, rx_pos, state,
 * authenticated, and full_jid from a previous client will persist.
 * Add: memset(ctx, 0, sizeof(*ctx)); after selecting the slot.
 * ------------------------------------------------------------------ */
err_t xmpp_accept_callback(void *arg, struct tcp_pcb *newpcb, err_t err) {
    static xmpp_client_ctx_t client_pool[MAX_USERS];
    static int client_idx = 0;

    xmpp_client_ctx_t *ctx = &client_pool[client_idx];
    client_idx = (client_idx + 1) % MAX_USERS;

    /* TODO: memset(ctx, 0, sizeof(*ctx)); here to prevent state bleed */

    ctx->pcb = newpcb;
    ctx->state = STATE_CONNECTED;
    ctx->authenticated = 0;

    tcp_arg(newpcb, ctx);

    tcp_recv(newpcb, xmpp_recv_callback);

    return ERR_OK;
}

/* ------------------------------------------------------------------
 * xmpp_init_server
 *
 * Binds and starts listening on the XMPP client port.
 *
 * RFC 6120 §3.2  — Client-to-Server connections:
 *   TCP port 5222 (IANA registered as "xmpp-client").
 *   https://datatracker.ietf.org/doc/html/rfc6120#section-3.2
 *
 * TODO: RFC 6120 §5 — also listen on port 5223 for "Direct TLS"
 *   (legacy XEP-0035 / RFC 6120 §5.3.2) if TLS is added.
 * ------------------------------------------------------------------ */
void xmpp_init_server() {
    struct tcp_pcb *pcb = tcp_new();

    tcp_bind(pcb, IP_ADDR_ANY, 5222); /* RFC 6120 §3.2 — XMPP client port */

    pcb = tcp_listen(pcb);

    tcp_accept(pcb, xmpp_accept_callback);
}